"""baseline - existing schema

Revision ID: 42a320ad6145
Revises: acc08fcc1e7f
Create Date: 2026-06-28 10:56:02.427931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a320ad6145'
down_revision = 'acc08fcc1e7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('avatar_public_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_public_id')
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
